### ISSUE TITLE
Error in console, Template parse errors

### ISSUE THREAD

**Issue by rajeshd50** [DethAriel/ng2-recaptcha#4]
HI, 
I'm using anular-cli for this project. 
-  Typescript version is 2.0.2
- Angular 2.0.0
- ng2-recaptcha 1.3.2

I've installed the typing using the following command

> npm install @types/grecaptcha --save-dev

My root app module looks like this

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule,CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { RecaptchaModule } from 'ng2-recaptcha';
import { routes } from './app-routing.module';
import { AppComponent } from './app.component';
import { UserModule } from './user/user.module';
import { SharedModule } from './shared/shared.module';
import { ToasterModule, ToasterService } from 'angular2-toaster/angular2-toaster';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    RecaptchaModule.forRoot(),
    ToasterModule,
    RouterModule.forRoot(routes, { useHash: true }),
    SharedModule.forRoot(),
    UserModule
  ],
  providers: [ToasterService],
  bootstrap: [AppComponent],
  exports: [],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AppModule { }
```
After importing the module, in another module, UserModule (which is imported here) I'm using the <recaptcha> element.

Thats when I'm getting this error in browser console.
> zone.js:355Unhandled Promise rejection: Template parse errors:
> 'recaptcha' is not a known element:

> If 'recaptcha' is an Angular component, then verify that it is part of this  module.

> If 'recaptcha' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.

After first time getting this message I added CUSTOM_ELEMENTS_SCHEMA in my root module as seen above, even after that I'm getting the same error.

Where I'm going wrong?

Thanks..

**Comment by DethAriel** [comment]
There are two ways of fixing that:

1. Add `RecaptchaModule` to the `imports` section of your `UserModule`
2. Add `RecaptchaModule` to the `imports` section of your `SharedModule` (given that you import `SharedModule` inside `UserModule`)

In both cases you should still leave the `RecaptchaModule.forRoot()` import in your `AppModule`.

Please, let me know if that resolves the issue that you see

**Comment by rajeshd50** [comment]
Hi, 
I've imported the recaptcha module in userModule, after that its working fine. Thanks. The issue is resolved now.
But one thing, importing the module in root component allow its child components to use the module, Hierarchical injection. Is this the case ? 
Thanks again for helping.

**Comment by DethAriel** [comment]
I'm glad the issue is resolved. However, modules work a bit different from what you described. A module only knows about stuff that's specified in its "imports" section, no more, no less. Imports are propagated from bottom up, e.g. if module X imports module Y, which in turn imports module Z, then module X will know about both Y and Z (that's why `SharedModule` is so useful). On the other hand, if module A imports modules B and C (the way it was in your configuration), that doesn't mean that B will know about C.Hopefully this will clarify things a bit.






On Tue, Oct 11, 2016 at 7:07 PM -0700, "Rajesh Dan" <notifications@github.com> wrote:












Hi, 

I've imported the recaptcha module in userModule, after that its working fine. Thanks. The issue is resolved now.

But one thing, importing the module in root component allow its child components to use the module, Hierarchical injection. Is this the case ? 

Thanks again for helping.

**Comment by rajeshd50** [comment]
Thank a lot. Got the point. Now everything is working great. :)

**Comment by nitishatambi** [comment]
I used this, but getting error in re-captcha tag in html page

![image](https://user-images.githubusercontent.com/26836300/37555417-c77f3e8c-2a0c-11e8-9bd4-6a1da2bf94e1.png)
